DATASET:
  num_samples: 2000
  n_train: 1400
  n_val: 400
  n_test: 200
  noise: 0.6
  equal_density: true

  batch_size: 32
  num_workers: 4
  seed: 0



EXPERIMENT:
  name: 'ToyExperiment'
  out_model: './checkpoints/'
  log_path: './outputs/'
  resume: false

  wdecay: 0.001
  optim_lr: 0.001
  optim_momentum: 0.9
  used_nesterov: False
  use_gpu: true

  n_epoch: 1000
  save_every: 100
  save_model: false

  plot_every: 100

hydra:
  run:
    dir: ./