DATASET:
  num_samples: 2000
  n_train: 1400
  n_val: 400
  n_test: 200
  noise: 0.3
  equal_density: False

  batch_size: 32
  num_workers: 4
  seed: 1265

MODEL:
  h_nodes: [2, 16]
  out_dim: 1
  activation: 'relu' # or leakyRelU
  use_bn: False
  fc_winit: 'he_normal'
  fc_binit: 'zeros'
  bn_winit: 'ones'
  bn_binit: 'zeros'

EXPERIMENT:
  name: 'ToyExperiment'
  log_path: './outputs/testTrain/'

  TH: 0.5
  wdecay: 0.0001
  optim_lr: 0.0001
  optim_momentum: 0.9
  used_nesterov: False
  use_gpu: True

  n_epoch: 10
  plot_every: 10 # not plot during training if 0

  save_model: True
  save_every: 10
  out_model: './checkpoints/'
  resume: False
  resume_checkpoints: './checkpoints/ToyExperiment_epoch_9.pth.tar'

Logging:
  name: "LR"
  seed: 1265   

hydra:
  run:
    dir: ./