#TODO: add available choices
defaults:
  - dataset: spiral
  - init_methods@MODEL.fc_winit: normal_custom
  - init_methods@MODEL.fc_binit: default
  - init_methods@MODEL.bn_winit: ones
  - init_methods@MODEL.bn_binit: zeros

Logging:
  name: "LR"
  seed: ${DATASET.seed}

DATASET:
  fixed_valset: True
  fixed_val_factor: 1

MODEL:
  seed: ${DATASET.seed}
  input_dim: len(${DATASET.increase_dim}) * 2 + 2
  h_nodes: [16]
  out_dim: 1
  activation: 'relu' # or leakyRelU
  use_bn: False

EXPERIMENT:
  name: 'ToyExperiment'
  framework: lightning
  wandb_project: degree-project-lit
  debug: False
  # wandb setting
  dryrun: False

  # classification
  TH: 0.5
  wdecay: 0.001
  dis_reg: 0.00 # coefficient of distance reg term 
  reg_filter: composite_relu # or abs_relu, or sqrt_relu

  # optimizer
  optim_lr: 0.001
  optim_momentum: 0.9
  warmup: 0
  used_nesterov: True
  early_stop: False
  use_gpu: True
  ema_used: True
  ema_decay: 0.999

  n_epoch: 1024
  steps_per_epoch: np.ceil(${DATASET.n_train} / ${DATASET.batch_size})
  plot_every: 64
  plot_points: False
  plot_confidence: True
  TH_bounds: [-0.2, 0.2]

  save_model: True
  save_every: 64
  #TODO: MODEL.fc_winit.params.gain might not be in struct
  out_folder: ${EXPERIMENT.name}_${DATASET.name}_${MODEL.fc_winit.name}_${MODEL.fc_binit.name}_${EXPERIMENT.TH_bounds}_seed${Logging.seed}_${now:%Y-%m-%d_%H-%M-%S} # log & tfevents under ./outputs, checkpoints under ./checkpoints

  resume: False
  resume_checkpoints: './checkpoints/ToyExperiment_epoch_0.pth.tar' # folder or file
  resumed_epochs: [0,1023]


hydra:
  run:
    dir: ./outputs/${EXPERIMENT.out_folder}
