#TODO: add available choices
defaults:
  - dataset: synthetic
  - init_methods@MODEL.fc_winit: xavier_uniform
  - init_methods@MODEL.fc_binit: range_uniform
  - init_methods@MODEL.bn_winit: ones
  - init_methods@MODEL.bn_binit: zeros

Logging:
  name: "LR"
  seed: 0

MODEL:
  h_nodes: [2, 32]
  out_dim: 1
  activation: 'relu' # or leakyRelU
  use_bn: False

EXPERIMENT:
  name: 'ToyExperiment'

  # classification
  TH: 0.5
  wdecay: 0.0005
  bdecay: 0.000 # bias decay TODO: only applied for circle_fill data
  bdecay_mean: (${MODEL.fc_binit.params.b} + ${MODEL.fc_binit.params.a})/2
  bdecay_method: l1

  # optimizer
  optim_lr: 0.001
  optim_momentum: 0.9
  warmup: 0
  used_nesterov: False
  use_gpu: True

  n_epoch: 1024
  steps_per_epoch: np.ceil(${DATASET.n_train} / ${DATASET.batch_size})
  plot_every: 64
  plot_points: False
  plot_confidence: True
  TH_bounds: [-0.2, 0.2]

  save_model: True
  save_every: 64
  #TODO: MODEL.fc_winit.params.gain might not be in struct
  out_folder: ${DATASET.name}_${MODEL.fc_winit.name}_${MODEL.fc_binit.name}_${EXPERIMENT.TH_bounds}_seed${Logging.seed}_${now:%Y-%m-%d_%H-%M-%S} # log & tfevents under ./outputs, checkpoints under ./checkpoints

  resume: False
  resume_checkpoints: './checkpoints/ToyExperiment_epoch_0.pth.tar' # folder or file
  resumed_epochs: [0,1023]


hydra:
  run:
    dir: ./outputs/${EXPERIMENT.out_folder}
