#@package _global_
DATASET:
  name: 'iris'
  seed: 0
  # make data
  species_id: [2,3] # [1,2,3]

# plot linear regions
EXPERIMENT:
  plot_LR: False
  plot_every: 10 # not plot linear regions
  plotted_axis: [0,1]
  plot_confidence: True # works only when plot_every > 0
  TH_bounds: [0.45, 0.55] # used to tell if a lr is in the boundary