#@package _global_
DATASET:
  name: 'titanic'
  seed: 0
  # make data
  species_id: [1,2] # selecct two from [1,2,3]
  shuffle: True

  # data loader
  n_train: 0.7
  n_val: 0.2
  n_test: 0.1
  batch_size: 32
  num_workers: 4

# plot linear regions
EXPERIMENT:
  plot_every: 0 # not plot linear regions
  plotted_axis: [0,1]
  plot_confidence: True # works only when plot_every > 0
  TH_bounds: [0.45, 0.55] # used to tell if a lr is in the boundary