#@package _global_
DATASET:
  name: 'moons'
  # make data
  n_samples: 2000
  equal_density: False # only used for circles
  width: 0.05
  gap: 1 # boundary_width [0, 1) for circles, 
  noise_ratio: 0 # percent of noisy points
  noise_level: 0.2 # guassian std noise
  shuffle: True
  fixed_valset: 0 # if fixed_valset==0, the size of valset will decided by n_val
  
# plot linear regions
EXPERIMENT:
  plot_LR: True
  plot_every: 10
  plot_confidence: True
  TH_bounds: [-0.2, 0.2] # used to tell if a lr is in the boundary