#@package _global_
DATASET:
  name: 'moons'
  seed: 0
  # make data
  total_samples: 2000
  equal_density: False # only used for circles
  width: 0.05
  boundary_w: 1 # boundary_width [0, 1) for circles, 
  noise_ratio: 0 # percent of noisy points
  noise_level: 0.2 # guassian std noise
  shuffle: True
  increase_dim: [] # [np.cos, np.sin, np.square]

  # data loader
  n_train: 0.7
  n_val: 0.1
  n_test: 0.2
  batch_size: 32
  num_workers: 4

# plot linear regions
EXPERIMENT:
  plot_LR: True
  plot_every: 10
  plot_confidence: True
  TH_bounds: [-0.2, 0.2] # used to tell if a lr is in the boundary