#@package _global_
DATASET:
  name: 'sphere'
  seed: 0
  # make data
  r: 0.1
  w: 0.05
  center0: [0.5,0.5,0.5]
  center1: [0.25,0.25,0.25]
  Nfactor: 50
  fixed_val_factor: 20
  shuffle: True

  # data loader
  n_train: 0.7
  n_val: 0.2
  n_test: 0.1
  batch_size: 32
  num_workers: 4

# plot linear regions
EXPERIMENT:
  plot_LR: False
  plot_every: 10 # not plot linear regions
  plotted_axis: [0,1]
  plot_confidence: True # works only when plot_every > 0
  TH_bounds: [0.45, 0.55] # used to tell if a lr is in the boundary