#@package _global_
DATASET:
  name: 'spiral'
  seed: 0
  # make data
  factor: 50
  total_samples: ${DATASET.factor} * 97 * 2
  width: 0.008 # band width
  
  noise_ratio: 0 # percent of noisy points
  noise_level: 0.2 # guassian std noise
  shuffle: True
  increase_dim: [] # [np.cos, np.sin, np.square]

  # data loader
  n_train: 0.7
  n_val: 0.2
  n_test: 0.1
  batch_size: 32
  num_workers: 4

# plot linear regions
EXPERIMENT:
  plot_every: 10
  plot_confidence: True
  TH_bounds: [-0.2, 0.2] # used to tell if a lr is in the boundary