#@package _global_
DATASET:
  name: 'spiral'
  # make data
  n_samples: 50 # * The actuall trainsize will be n_samples*97*2 or n_samples*97*2*train_ratio if a train_ratio is specified
  width: 0.008 # band width
  
  noise_ratio: 0 # percent of noisy points
  noise_level: 0.2 # guassian std noise
  shuffle: True
  fixed_valset: 0 # if fixed_valset==0, the size of valset will decided by n_val

# plot linear regions
EXPERIMENT:
  plot_LR: False
  plot_every: 10
  plot_confidence: False
  TH_bounds: [-0.2, 0.2] # used to tell if a lr is in the boundary