#@package _global_
DATASET:
  # make data
  name: 'moons'
  total_samples: 2000
  noise: 0.05 

  # params for make_circle
  factor: 0.5 

  # params for make_circle_fill
  equal_density: False
  r1: [0, 1] # radius range of the inner circle
  r2: [4, 9] # radius range of the outer ring

  # data loader
  n_train: 1400
  n_val: 400
  n_test: 200
  batch_size: 32
  num_workers: 4